<a href="https://colab.research.google.com/github/karrthikmohank/PythonPrograms/blob/main/NumpyAssignmentsSolutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Write a Python program to print the NumPy version in your system.

In [ ]:
import numpy as np
print(np.version.version)
print(np.__version__)

1.21.6
1.21.6


# Write a Python program to reverse an array (first element becomes last).

In [ ]:
import numpy as np
while(True):
  lst1 = eval(input("Enter a list: "))
  numArray = np.array(lst1)
  numArray = numArray[::-1]  
  print(f"The reversed array: {numArray}")
  toContinue = input("Do you want to continue (Y/N)?? ")
  toContinue = toContinue.upper()
  if (toContinue == "Y"):
    continue
  else:
    print("Exiting Program - Thank you !!")
    break

Enter a list: [1,2,3,4,5]
The reversed array: [5 4 3 2 1]
Do you want to continue (Y/N)?? y
Enter a list: [1,2,3,4,5,6]
The reversed array: [6 5 4 3 2 1]
Do you want to continue (Y/N)?? n
Exiting Program - Thank you !!


# Write a Python program to convert a list and tuple into arrays.

In [ ]:
import numpy as np
lst1 = [1,2,3,4,5,6]
print("Lists: ")
print("Input: ",end = "")
print(lst1)
print("Converting list to array: ")
print("Output: ",end = "")
print(np.asarray(lst1))
print(type(np.asarray(lst1)))

lst2 = [[1,2,3],[4,5,6]]
print("\nInput: ",end = "")
print(lst2)
print("Converting list to array: ")
print("Output: ",end = "")
print(np.asarray(lst2))
print(type(np.asarray(lst2)))

print("\nTuples: ")
tuple1 = (1,2,3,4,5,6)
print("Input: ",end = "")
print(tuple1)
print("Converting tuple to array: ")
print(np.asarray(tuple1))
print(type(np.asarray(tuple1)))

tuple2 = ((1,2,3),(4,5,6))
print("\nInput: ",end = "")
print(tuple2)
print("Converting tuple to array: ")
print(np.asarray(tuple2))
print(type(np.asarray(tuple2)))

Lists: 
Input: [1, 2, 3, 4, 5, 6]
Converting list to array: 
Output: [1 2 3 4 5 6]
<class 'numpy.ndarray'>

Input: [[1, 2, 3], [4, 5, 6]]
Converting list to array: 
Output: [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

Tuples: 
Input: (1, 2, 3, 4, 5, 6)
Converting tuple to array: 
[1 2 3 4 5 6]
<class 'numpy.ndarray'>

Input: ((1, 2, 3), (4, 5, 6))
Converting tuple to array: 
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# Write a Python program to find common values between two arrays.

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,8,9,10])
print("Input arrays: ")
print("Array 1: ")
print(arr1)
print("Array 2: ")
print(arr2)
arr3 = np.intersect1d(arr1,arr2)
print("Common values:")
print(arr3)

Input arrays: 
Array 1: 
[1 2 3 4 5 6]
Array 2: 
[ 4  5  6  8  9 10]
Common values:
[4 5 6]


# Write a Python program compare two arrays using numpy.

# Using ndarray.all() method

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
print("Array 1: \n",arr1)
print("Array 2: \n",arr2)
compare = arr1 == arr2
isEqual_1_2 = compare.all()
print("Is the arrays equal? ",isEqual_1_2)
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[4,5,6],[1,2,3]])
print("Array 3: \n",arr3)
print("Array 4: \n",arr4)
compare = arr3 == arr4
# print(compare)
isEqual_3_4 = compare.all()
print("Is the arrays equal? ",isEqual_3_4)


Array 1: 
 [[1 2 3]
 [4 5 6]]
Array 2: 
 [[1 2 3]
 [4 5 6]]
Is the arrays equal?  True
Array 3: 
 [[1 2 3]
 [4 5 6]]
Array 4: 
 [[4 5 6]
 [1 2 3]]
Is the arrays equal?  False


# Using np.greater, np.greater_equal, np.less and np.less_equal methods

In [ ]:
import numpy as np
print("************ 1-D arrays *****************")
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3,4,5,6])
print("Array 1: \n",arr1)
print("Array 2: \n",arr2)
print("Array 1 > Array 2\n",np.greater(arr1,arr2))
print("Array 1 >= Array 2\n",np.greater_equal(arr1,arr2))
print("Array 1 < Array 2\n",np.less(arr1,arr2))
print("Array 1 <= Array 2\n",np.less_equal(arr1,arr2))
print("******************************************")
arr3 = np.array([1,2,3,4,5,6])
arr4 = np.array([4,5,6,1,2,3])
print("Array 3: \n",arr3)
print("Array 4: \n",arr4)
print("Array 3 > Array 4\n",np.greater(arr3,arr4))
print("Array 3 >= Array 4\n",np.greater_equal(arr3,arr4))
print("Array 3 < Array 4\n",np.less(arr3,arr4))
print("Array 3 <= Array 4\n",np.less_equal(arr1,arr4))

print("************ 2-D arrays *****************")
arr5 = np.array([[1,2,3],[4,5,6]])
arr6 = np.array([[1,2,3],[4,5,6]])
print("Array 5: \n",arr5)
print("Array 6: \n",arr6)
print("Array 5 > Array 6\n",np.greater(arr5,arr6))
print("Array 5 >= Array 6\n",np.greater_equal(arr5,arr6))
print("Array 5 < Array 6\n",np.less(arr5,arr6))
print("Array 5 <= Array 6\n",np.less_equal(arr5,arr6))
print("******************************************")
arr7 = np.array([[1,2,3],[4,5,6]])
arr8 = np.array([[4,5,6],[1,2,3]])
print("Array 7: \n",arr7)
print("Array 8: \n",arr8)
print("Array 7 > Array 8\n",np.greater(arr7,arr8))
print("Array 7 >= Array 8\n",np.greater_equal(arr7,arr8))
print("Array 7 < Array 8\n",np.less(arr7,arr8))
print("Array 7 <= Array 8\n",np.less_equal(arr7,arr8))

************ 1-D arrays *****************
Array 1: 
 [1 2 3 4 5 6]
Array 2: 
 [1 2 3 4 5 6]
Array 1 > Array 2
 [False False False False False False]
Array 1 >= Array 2
 [ True  True  True  True  True  True]
Array 1 < Array 2
 [False False False False False False]
Array 1 <= Array 2
 [ True  True  True  True  True  True]
******************************************
Array 3: 
 [1 2 3 4 5 6]
Array 4: 
 [4 5 6 1 2 3]
Array 3 > Array 4
 [False False False  True  True  True]
Array 3 >= Array 4
 [False False False  True  True  True]
Array 3 < Array 4
 [ True  True  True False False False]
Array 3 <= Array 4
 [ True  True  True False False False]
************ 2-D arrays *****************
Array 5: 
 [[1 2 3]
 [4 5 6]]
Array 6: 
 [[1 2 3]
 [4 5 6]]
Array 5 > Array 6
 [[False False False]
 [False False False]]
Array 5 >= Array 6
 [[ True  True  True]
 [ True  True  True]]
Array 5 < Array 6
 [[False False False]
 [False False False]]
Array 5 <= Array 6
 [[ True  True  True]
 [ True  True  True]]
***

# Using array_equal() method

In [ ]:
import numpy as np
print("************ 1-D arrays *****************")
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3,4,5,6])
print("Array 1: \n",arr1)
print("Array 2: \n",arr2)
print("Array 1 > Array 2\n",np.array_equal(arr1,arr2))
print("******************************************")
arr3 = np.array([1,2,3,4,5,6])
arr4 = np.array([4,5,6,1,2,3])
print("Array 3: \n",arr3)
print("Array 4: \n",arr4)
print("Array 3 > Array 4\n",np.array_equal(arr3,arr4))

print("************ 2-D arrays *****************")
arr5 = np.array([[1,2,3],[4,5,6]])
arr6 = np.array([[1,2,3],[4,5,6]])
print("Array 5: \n",arr5)
print("Array 6: \n",arr6)
print("Array 5 > Array 6\n",np.array_equal(arr5,arr6))
print("******************************************")
arr7 = np.array([[1,2,3],[4,5,6]])
arr8 = np.array([[4,5,6],[1,2,3]])
print("Array 7: \n",arr7)
print("Array 8: \n",arr8)
print("Array 7 > Array 8\n",np.array_equal(arr7,arr8))


************ 1-D arrays *****************
Array 1: 
 [1 2 3 4 5 6]
Array 2: 
 [1 2 3 4 5 6]
Array 1 > Array 2
 True
******************************************
Array 3: 
 [1 2 3 4 5 6]
Array 4: 
 [4 5 6 1 2 3]
Array 3 > Array 4
 False
************ 2-D arrays *****************
Array 5: 
 [[1 2 3]
 [4 5 6]]
Array 6: 
 [[1 2 3]
 [4 5 6]]
Array 5 > Array 6
 True
******************************************
Array 7: 
 [[1 2 3]
 [4 5 6]]
Array 8: 
 [[4 5 6]
 [1 2 3]]
Array 7 > Array 8
 False


# Write a Python program to change the dimension of an array.

# Using array_name.shape() method

In [ ]:
import numpy as np
print("************ 1-D arrays *****************")
arr1 = np.array([1,2,3,4,5,6])
print("Array 1: \n",arr1)
# checking current shape
print('Current shape of the array')
print(arr1.shape)
arr1.shape = (3,2)
print('Changing shape to 3,2')
print(arr1)

print("************ 2-D arrays *****************")
arr2 = np.array([[1,2,3],[4,5,6]])
print("Array 2: \n",arr2)
# checking current shape
print('Current shape of the array')
print(arr2.shape)
arr2.shape = (6,)
print('Changing shape to 1D array with six elements')
print(arr2)

************ 1-D arrays *****************
Array 1: 
 [1 2 3 4 5 6]
Current shape of the array
(6,)
Changing shape to 3,2
[[1 2]
 [3 4]
 [5 6]]
************ 2-D arrays *****************
Array 2: 
 [[1 2 3]
 [4 5 6]]
Current shape of the array
(2, 3)
Changing shape to 1D array with six elements
[1 2 3 4 5 6]


# Using reshape method

In [ ]:
import numpy as np
print("************ 1-D arrays *****************")
arr1 = np.array([1,2,3,4,5,6])
print("Array 1: \n",arr1)
# checking current shape
print('Current shape of the array')
print(arr1.shape)
arr1 = arr1.reshape((3,2))
print('Changing shape to 3,2')
print(arr1)
print('Current shape of the array')
print(arr1.shape)

print("************ 2-D arrays *****************")
arr2 = np.array([[1,2,3],[4,5,6]])
print("Array 2: \n",arr2)
# checking current shape
print('Current shape of the array')
print(arr2.shape)
arr2 = arr2.reshape((6,))
print('Changing shape to 1D array with six elements')
print(arr2)
print('Current shape of the array')
print(arr2.shape)

************ 1-D arrays *****************
Array 1: 
 [1 2 3 4 5 6]
Current shape of the array
(6,)
Changing shape to 3,2
[[1 2]
 [3 4]
 [5 6]]
Current shape of the array
(3, 2)
************ 2-D arrays *****************
Array 2: 
 [[1 2 3]
 [4 5 6]]
Current shape of the array
(2, 3)
Changing shape to 1D array with six elements
[1 2 3 4 5 6]
Current shape of the array
(6,)


# Using resize method

In [ ]:
import numpy as np
print("************ 1-D arrays *****************")
arr1 = np.array([1,2,3,4,5,6])
print("Array 1: \n",arr1)
# checking current shape
print('Current shape of the array')
print(arr1.shape)
arr1 = np.resize(arr1,(3,2))
print('Changing shape to 3,2')
print(arr1)
print('Current shape of the array')
print(arr1.shape)

print("************ 2-D arrays *****************")
arr2 = np.array([[1,2,3],[4,5,6]])
print("Array 2: \n",arr2)
# checking current shape
print('Current shape of the array')
print(arr2.shape)
arr2 = np.resize(arr2,(6,))
print('Changing shape to 1D array with six elements')
print(arr2)

************ 1-D arrays *****************
Array 1: 
 [1 2 3 4 5 6]
Current shape of the array
(6,)
Changing shape to 3,2
[[1 2]
 [3 4]
 [5 6]]
Current shape of the array
(3, 2)
************ 2-D arrays *****************
Array 2: 
 [[1 2 3]
 [4 5 6]]
Current shape of the array
(2, 3)
Changing shape to 1D array with six elements
[1 2 3 4 5 6]


# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

In [ ]:
import numpy as np
number = 1
arr1 = np.array([])
while number <= 100:
  if ( (number % 3) == 0 ) or ( (number % 5) == 0 ):
    arr1 = np.append(arr1,[number])    
  number += 1
print("Sum of multiples of 3 or 5 below 100 is ",np.sum(arr1))

Sum of multiples of 3 or 5 below 100 is  2418.0


# # Write a Python program to convert a NumPy array into Python list structure. 

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
lst1 = arr1.tolist()
print(lst1,type(lst1))
arr2 = np.array([[1,2,3],[4,5,6]])
lst2 = arr2.tolist()
print(lst2,type(lst2))

[1, 2, 3, 4, 5, 6] <class 'list'>
[[1, 2, 3], [4, 5, 6]] <class 'list'>


# Write a Python program to how to add an extra column to a numpy array.

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print("Array 1: \n",arr1)
z1 = np.zeros((2,1),dtype=int)
arr1 = np.append(arr1,z1,axis=1)
print("Output Array: \n",arr1)

Array 1: 
 [[1 2 3]
 [4 5 6]]
Output Array: 
 [[1 2 3 0]
 [4 5 6 0]]


# Using hstack method

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print("Array 1: \n",arr1)
arr1 = np.hstack((arr1, np.zeros((arr1.shape[0], 1), dtype=arr1.dtype)))
print("Output Array: \n",arr1)

Array 1: 
 [[1 2 3]
 [4 5 6]]
Output Array: 
 [[1 2 3 0]
 [4 5 6 0]]


# # Write a Python program to check whether the numpy array is empty or not.

#Using size method

In [ ]:
import numpy as np
print("************ 1-D arrays *****************")
arr1 = np.array([1,2,3,4,5,6])
print("Array 1: \n",arr1)
# checking size of the array
if arr1.size == 0:
  print("Array is empty!!!")
else:
  print("Array is not empty!!!")
  print('Size of the array',arr1.size)

arr2 = np.array([])
print("Array 2: \n",arr2)
# checking size of the array
if arr2.size == 0:
  print("Array is empty!!!")
else:
  print("Array is not empty!!!")
  print('Size of the array',arr2.size)

print("************ 2-D arrays *****************")
arr3 = np.array([[1,2,3],[4,5,6]])
print("Array 3: \n",arr3)
# checking current size of the array
if arr3.size == 0:
  print("Array is empty!!!")
else:
  print("Array is not empty!!!")
  print('Size of the array',arr3.size)


************ 1-D arrays *****************
Array 1: 
 [1 2 3 4 5 6]
Array is not empty!!!
Size of the array 6
Array 2: 
 []
Array is empty!!!
************ 2-D arrays *****************
Array 3: 
 [[1 2 3]
 [4 5 6]]
Array is not empty!!!
Size of the array 6


# Use any method

In [ ]:
import numpy as np
arr = np.array([1,3])
flag = not np.any(arr)
print(flag)
if flag:
    print('Array is empty')
else:
    print('Array is not empty')

False
Array is not empty


# Write a Python program to normalize a 3x3 random matrix.

In [6]:
import numpy as np
normArr = np.zeros((3,3))
arr1 = np.random.random((3,3))
print("Original array: ")
print(arr1)
rangeToNormalize = (0,1)
rangeDiff = rangeToNormalize[1] - rangeToNormalize[0]
minValue, maxValue = arr1.min(),arr1.max()
diffMaxMin = maxValue - minValue
for rows in range(3):
  for cols in range(3):
    temp = ( ((arr1[rows][cols] - minValue)*rangeDiff)/(maxValue - minValue) ) + rangeToNormalize[0]
    normArr[rows][cols] = temp
print("After normalization: ")
print(normArr)

Original array: 
[[0.10231139 0.15264396 0.54948961]
 [0.57257538 0.96222774 0.7056882 ]
 [0.18298468 0.36236186 0.8198153 ]]
After normalization: 
[[0.         0.05853194 0.52002525]
 [0.54687179 1.         0.70166919]
 [0.09381528 0.30241369 0.83438803]]


# How to ignore all numpy warnings (not recommended)?

In [5]:
import warnings
warnings.filterwarnings('ignore')



# How to swap two rows of an array?

In [7]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("Original array: ")
print(arr1)
arr1[[0,2],:] = arr1[[2,0],:]
print("Output array: ")
print(arr1)

Original array: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Output array: 
[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]


# Python program to create a random vector of size 10 and sort it.

In [9]:
import numpy as np
arr1 = np.random.random(10)
print("Original array: ")
print(arr1)
print("Sorted array: ")
arr1.sort()
print(arr1)

Original array: 
[0.84444721 0.48398903 0.78084259 0.92746288 0.60888768 0.70616572
 0.18859749 0.69736733 0.52810243 0.78490621]
Sorted array: 
[0.18859749 0.48398903 0.52810243 0.60888768 0.69736733 0.70616572
 0.78084259 0.78490621 0.84444721 0.92746288]


# Write a Python program to check two random arrays are equal or not.

In [12]:
import numpy as np
arr1 = np.random.random(10)
print("Array 1: ")
print(arr1)
arr2 = np.random.random(10)
print("Array 2: ")
print(arr2)
isEqual12 = np.allclose(arr1,arr2)
print("Is array 1 and array 2 are equal or not?",isEqual12)
arr3 = arr1
print("Array 3: ")
print(arr3)
isEqual13 = np.allclose(arr1,arr3)
print("Is array 1 and array 3 are equal or not?",isEqual13)

Array 1: 
[0.64574143 0.0477903  0.38523772 0.07437624 0.49794699 0.39490577
 0.2649388  0.04123563 0.66259083 0.30210094]
Array 2: 
[0.53567102 0.44979034 0.6576236  0.85277206 0.87186667 0.15497273
 0.98416698 0.53533007 0.61526703 0.6853189 ]
Is array 1 and array 2 are equal or not? False
Array 3: 
[0.64574143 0.0477903  0.38523772 0.07437624 0.49794699 0.39490577
 0.2649388  0.04123563 0.66259083 0.30210094]
Is array 1 and array 3 are equal or not? True


# Write a Python program to add, subtract, multiply, divide arguments element-wise.

In [17]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
print("Addition of arrays: ")
print(np.add(arr1,arr2))
print("Subtraction of arrays: ")
print(np.subtract(arr1,arr2))
print("Multiplication of arrays: ")
print(np.multiply(arr1,arr2))
print("Division of arrays: ")
print(np.divide(arr1,arr2))


Addition of arrays: 
[[ 8 10 12]
 [14 16 18]]
Subtraction of arrays: 
[[-6 -6 -6]
 [-6 -6 -6]]
Multiplication of arrays: 
[[ 7 16 27]
 [40 55 72]]
Division of arrays: 
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# Write a Python program to get the dates of yesterday, today and tomorrow.

In [21]:
import numpy as np
today = np.datetime64("today","D")
print("Today's date: ",today)

tomorrow = np.datetime64("today","D") + np.timedelta64(1,"D")
print("Tomorrow's date: ",tomorrow)

yesterday = np.datetime64("today","D") - np.timedelta64(1,"D")
print("Yesterday's date: ",yesterday)

Today's date:  2022-10-05
Tomorrow's date:  2022-10-06
Yesterday's date:  2022-10-04
